name: todo_clone
description: Task manager App by Abbos Donaboyev

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  intl: ^0.17.0
  floor: ^1.1.0
  auto_route: ^3.2.4
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  keyboard_dismisser: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  flutter_lints: ^1.0.4
  floor_generator: ^1.1.0
  auto_route_generator: ^3.2.3
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/png/ic_app_logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
