name: todo_clone
description: Task manager App by Abbos Donaboyev

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.17.0
  floor: ^1.2.0
  equatable: ^2.0.3
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  moor_flutter: ^4.1.0
  url_launcher: ^6.1.3
  cupertino_icons: ^1.0.5
  modal_bottom_sheet: ^2.0.1
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^1.0.4
  floor_generator: ^1.2.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/images/png/ic_app_logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
